name: Build

on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
      - name: Create API Key
        run: echo "FLAPP_API_KEY=${{ secrets.REDDIT_API_KEY }}" > .env
      - name: Get flutter dependencies
        run: flutter pub get
      - name: Build application
        run: flutter build apk lib/src/main.dart --profile
      - name: Set Build name
        run: mv ./build/app/outputs/flutter-apk/app-profile.apk flapp.apk
      - name: Publish Release
        if: github.ref == 'refs/heads/master' 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: flapp.apk
      
